apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: website
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - image: amielmartin/olympiacodes-website:1.10.0-22-gacc7f83
          name: website
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            # - name: MEETUP_NAME
            #   value: olympiacodes
            # - name: TWITTER_USERNAME
            #   value: olympiacodes
            # - name: INSTAGRAM_USERNAME
            #   value: olympiacodes
            - name: FACEBOOK_PAGE
              value: olympiacodes
            - name: SLACK_TEAM
              valueFrom:
                secretKeyRef:
                  name: slack
                  key: team
            - name: SLACK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack
                  key: token
            - name: MAILCHIMP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: mailchimp
                  key: token
            - name: MAILCHIMP_LIST
              valueFrom:
                secretKeyRef:
                  name: mailchimp
                  key: list
